### ISSUE TITLE
Update to work with IDEA 15 EAP

### ISSUE THREAD

**Issue by extesy** [JetBrains/la-clojure#91]
This plugin doesn't show up for IntelliJ IDEA 15 EAP.

**Comment by donnerpeter** [comment]
The development of this plugin has been stopped, please use https://cursiveclojure.com/ instead.

**Comment by extesy** [comment]
@donnerpeter This sounds promising, thanks for the link. But Cursive doesn't support IDEA 15 either.

**Comment by cursiveclojure** [comment]
@extesy IDEA 15 support will come in the next couple of releases.

**Comment by Alefas** [comment]
I added appropriate information to readme file: https://github.com/JetBrains/la-clojure/commit/cd014589e53ec8acf24cfb293c7f2e7a7e474f6e
